### ISSUE TITLE
Error cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by Bartekus** [cloudposse/terraform-aws-jenkins#33]
So the pipeline works great until after it connects to the github, gets the new commit and then during docker build it fails as it tries to connect to the docker daemon.

![docker-error](https://user-images.githubusercontent.com/7887446/45637324-0696b680-ba5f-11e8-8f26-e4294bee428f.jpg)

Why is docker not accessible? Or is there something that's misconfigured here?

**Comment by Bartekus** [comment]
So I was not able to figure out how to ensure that all docker builds are run with the following two flags added: 
`-v /var/run/docker.sock:/var/run/docker.sock --name jenkins`

So I've resorted to modifying the jenkins repo from which terraform-aws-jenkins will build as such:
```
# https://hub.docker.com/r/jenkinsci/blueocean/tags/
FROM jenkinsci/blueocean:latest

USER root

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh gettext make docker shadow

RUN groupmod -g 1000 jenkins && \
    groupmod -g 994 docker

# Allow the jenkins user to run docker
RUN adduser jenkins docker && \
    usermod -a -G docker jenkins

# Uhh ohh this is dirty... and bad... probably would be safer to just run as root lol
RUN chmod 777 /var/run/docker.sock

# Drop back to the regular jenkins user
USER jenkins
...
``` 
Any suggestions regarding this predicament?

**Comment by osterman** [comment]
@Bartekus sounds like you're trying to do docker-in-docker (DnD) with jenkins on Elastic Beanstalk? Am I correct?

**Comment by Bartekus** [comment]
@osterman that is correct, am I walking the wrong path?

**Comment by osterman** [comment]
@Bartekus that's a pretty reasonable/common use-case, however, I would recommend doing that on the jenkins slaves, rather than on the master. 

Also, it's generally considered taboo to expose the docker socket to jobs because they are essentially granted root and can do bad things by bind-mounting the host filesystem. Thus, the "right" way to do it is using the DnD pattern. I think this is unfortunately out of scope for this module.

This is the gist of what I'm saying: https://github.com/tehranian/dind-jenkins-slave

**Comment by Bartekus** [comment]
Thank you @osterman as the higher mentioned repo should perhaps put me on the course of merging this supreme solution with the DnD requirement that I'm facing. It certainly seems like the two solution can be interwoven to fulfill such requirement, or am I overly optimistic and do not see the potential incompatibility between the two solutions?

**Comment by Bartekus** [comment]
To answer my own question:
In the `jenkins` repo, under `.ebextensions` directory I've modified `01-efs-mount.config` and added the following to the bottom of the `commands:` :
```
  03_add_privileged:
    cwd: /tmp
    command: 'sed -i "s/docker run -d/docker run --privileged -d --group-add docker -v \/var\/run\/docker.sock:\/var\/run\/docker.sock --name jenkins/" /opt/elasticbeanstalk/hooks/appdeploy/enact/00run.sh'
```
Again, this is temporary fix and I highly recommend against using it, especially in production environment, however extraordinary circumstances might need extraordinary 'hacks' to get by lol

**Comment by Bartekus** [comment]
The above still doesnt enable Docker in Docker functionality so yeah...

**Comment by Bartekus** [comment]
Excellent suggestion @osterman, thank you kindly for pointing me towards the proper/right implementation.

Meanwhile if anyone is looking for quick and dirty way of getting `jenkinsci/blueocean` working with your excellent terraform setup, these are the changes that I've made to the forked `cloudposse/jenkins` repo to make Docker-in-Docker work:

Dockerfile
```
# https://hub.docker.com/r/jenkinsci/blueocean/tags/
FROM jenkinsci/blueocean:latest

USER root

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh gettext make docker shadow

# Allow the jenkins user to run docker
RUN adduser jenkins docker && \
    usermod -a -G docker jenkins

# Drop back to the regular jenkins user
USER jenkins
...
```

.ebextensions/01-efs-mount.config
```
packages:
  yum:
    nfs-utils: []
    jq: []

commands:
  01_mount:
    command: "/tmp/mount-efs.sh"
  02_restart:
    # https://stackoverflow.com/questions/38180665/using-aws-efs-with-docker
    command: "service docker restart"
  03_add_privileged:
    cwd: /tmp
    command: 'sed -i "s/docker run -d/docker run --privileged --group-add docker -d/" /opt/elasticbeanstalk/hooks/appdeploy/enact/00run.sh'
...
```

.ebextensions/04-jenkins.config
```
container_commands:
  01_delete_init_groovy:
    command: "rm -f /var/jenkins_home/init.groovy.d/init.groovy"
    ignoreErrors: true
  02_delete_ec2_init_groovy:
    command: "rm -f /var/jenkins_home/init.groovy.d/init-ec2.groovy"
    ignoreErrors: true
  03_chmod_docker_sock:
    command: "chmod 777 /var/run/docker.sock"
    ignoreErrors: true
```

![it-works](https://user-images.githubusercontent.com/7887446/45751011-dd446a80-bbc5-11e8-83af-8ac125a2ee55.jpg)
